# Config for this:
#class ImputedIntensity(BaseParams):
#  input_file: Annotated[FilePath, AfterValidator(is_xlsx_file)]
#  index_col: int = 0
#  sheet_name: str
#
#  # metadata
#  metadata_file: Annotated[FilePath, AfterValidator(is_xlsx_file)]
#  metadata_sheet_name: str
#  metadata_index_col: int = 0
#  condition_col: str = "condition"
imputed_data:
  input_file: /home/mambauser/data/df_imputed.xlsx
  sheet_name: "Sheet1"

  metadata_file: /home/mambauser/data/df_imputed.xlsx
  metadata_sheet_name: "Sheet2"

# Config for this:
#class PreprocessParams(BaseParams):
#  norm_method: Literal["center.median", "standardize"] = "center.median"
#
#  # plots
#  n_rows: int
#  n_cols: int
#
#  # contrasts
#  gene_input_file: (
#    Annotated[FilePath, AfterValidator(is_xlsx_file)] | None
#  ) = None
#  contrasts: list[ContrastInput]
#
#class ContrastInput(TypedDict):
#  contrast: tuple[str, str]
#  genes_sheet: str | None
#  gene_list_col: str | None
preprocess:
  n_rows: 4
  n_cols: 2
  # which genes to run DE on - here we are just using the same genes as the imputed data
  gene_input_file: /home/mambauser/data/df_imputed.xlsx
  contrasts:
    # Order matters here. Here we are comparing MI vs SHAM
    - contrast:
        - "mi"
        - "sham"
      gene_list_col: Genes
      genes_sheet: "Sheet1"

#class RConfig(BaseModel):
#  rscript_bin: FilePath = "/opt/conda/bin/Rscript"
r:
  # location of Rscript binary. If running locally you can typically find it with `which Rscript`
  rscript_bin: /opt/conda/bin/Rscript

# Columns in the limma output. By default these are the columns that are expected
# to be output by limma.
limma_cols: &limma_cols
  gene_column: X
  lfc_column: logFC
  pval_column: adj.P.Val

# The full list of values that can be configured is at ./proteomics/analysis/deg_analysis/heatmap.py
# these are just the required values and commonly used ones
heatmap:
  # regex to replace in sample nsames to make it look nicer. If empty, no replacement is done
  col_name_replace_regex: "Abundance_"

# For the volcano and enrich plots, you only need to specify the width and height (in inches)
volcano:
  <<: *limma_cols
  width: 9
  height: 8.5

enrich:
  <<: *limma_cols
  width: 7
  height: 6
  # only enrichment for mmu and hsa are supported
  organism: "mmu"
