name: lfq-proteomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pip
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pingouin
  - jupyter
  - beautifulsoup4
  - openpyxl
  - python-igraph
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - conda-forge::r-base
  - conda-forge::r-renv
  - conda-forge::r-irkernel
  - conda-forge::r-tidyverse
  - conda-forge::r-essentials
  - conda-forge::r-gridextra
  - conda-forge::r-svglite
  - conda-forge::r-pheatmap
  - conda-forge::r-devtools
  - conda-forge::r-remotes
  - conda-forge::r-languageserver
  - conda-forge::r-gplots
  - conda-forge::r-here
  - conda-forge::r-patchwork
  - conda-forge::r-crayon
  - conda-forge::r-uuid
  - conda-forge::r-enrichr
  - conda-forge::r-factoextra
  - conda-forge::r-igraph
  - conda-forge::r-optparse
  - bioconda::bioconductor-qfeatures
  - bioconda::bioconductor-mscoreutils
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-genefilter
  - bioconda::bioconductor-dose
  - bioconda::bioconductor-org.hs.eg.db
  - bioconda::bioconductor-clusterprofiler
  - bioconda::bioconductor-enrichplot
  - bioconda::bioconductor-org.mm.eg.db
  - bioconda::bioconductor-enhancedvolcano
  - bioconda::bioconductor-annotationhub
  - bioconda::bioconductor-ensembldb
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger
  - conda-forge::r-lintr
  - pip:
      - pydantic
      - pyyaml
      - ruff
      - metaflow
      - MissForest

